name: Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Publish plugin
        run: dotnet publish src/Flow.Launcher.Plugin.Notion.csproj -c Release

      - name: Package artifact
        shell: pwsh
        run: |
          $zipPath = "Flow.Launcher.Plugin.Notion.zip"
          if (Test-Path $zipPath) { Remove-Item $zipPath }
          Compress-Archive -Path "src/bin/Release/net7.0-windows/publish/*" -DestinationPath $zipPath

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notion-plugin
          path: Flow.Launcher.Plugin.Notion.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: notion-plugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Flow.Launcher.Plugin.Notion.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
